# Generated by Django 4.2 on 2025-05-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferreguly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferreguly.empleado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_comprador_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_comprados', to='ferreguly.empleado'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferreguly.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferreguly.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_procesados', to='ferreguly.empleado'),
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('id_cliente__isnull', False), ('id_empleado__isnull', True)), models.Q(('id_cliente__isnull', True), ('id_empleado__isnull', False)), _connector='OR'), name='carrito_owner_check'),
        ),
    ]
